#!/usr/bin/env python

from util import printf,fprintf
import time
import util
import sys
import os
import re

def usage(prog):
    printf("Usage is %s <start> <stop>\n",prog)
    printf("\n")
    printf("Example %s 1 10\n",prog)
    printf("\n")
    printf("Will create hosts 1 through 10 with names\n")
    printf("n1.yourdomain n2.yourdomain n3.yourdomain etc\n")
    printf("based on what you used as your baseHost in the config.json\n")
    printf("file.\n")

if __name__ == "__main__":
    prog = sys.argv[0]
    if len(sys.argv)<3:
        usage(prog)
        sys.exit()
    config = util.load_json("config.json")
    first = int(sys.argv[1])
    last  = int(sys.argv[2])
    hosts = util.getHostsByNumber(config)
    old_nums = set(hosts.keys())
    new_nums = set(xrange(first,last+1))
    intersection = old_nums & new_nums
    if len(intersection)>0:
        old_names = [hosts[i]["name"] for i in intersection]
        printf("The below hosts already exist and this script")
        printf(" is refusing to continue\n")
        for i in intersection:
            printf("%s\n",hosts[i]["name"])
        sys.exit()
    for i in new_nums:
        host_name = "n%i%s"%(i,config["baseHost"])
        printf("Adding host: %s\n",host_name)
        resp = util.createServer(config,host_name)
        time.sleep(15.0) #The CloudServer guys recommended 
                         #a sleep of 15 seconds Between builds
        printf("%s\n",resp)
