#!/usr/bin/env python

from util import printf,fprintf
import util
import sys
import os
import re

def usage(prog):
    printf("Usage is %s <start> <stop>\n",prog)
    printf("\n")
    printf("Example %s 1 10\n",prog)
    printf("\n")
    printf("Will delete hosts 1 through 10 with names\n")
    printf("n1.yourdomain n2.yourdomain n3.yourdomain etc\n")
    printf("based on what you used as your baseHost in the config.json\n")
    printf("file.\n")

if __name__ == "__main__":
    prog = sys.argv[0]
    if len(sys.argv)<3:
        usage(prog)
        sys.exit()
    config = util.load_json("config.json")
    first = int(sys.argv[1])
    last  = int(sys.argv[2])
    hosts = util.getHostsByNumber(config)
    old_nums = set(hosts.keys())
    del_nums = set(xrange(first,last+1))
    dontexist = del_nums - old_nums
    if len(dontexist)>0:
        dontexistnames = ["n%i%s"%(i,config["baseHost"]) for i in dontexist]
        printf("The below hosts do not  exist and can not be deleted")
        for name in dontexistnames:
            printf("%s\n",name)
        del_nums = del_nums - dontexist# Takes care of bogus delete attempts
        printf("PFFT----------------------------------------------\n")
    for i in del_nums:
        host_name = hosts[i]["name"]
        host_id = hosts[i]["id"]
        printf("deleteing host: %s id=%i \n",host_name,host_id)
        resp = util.deleteServer(host_name)
        printf("%s\n",resp)
