#!/usr/bin/env python

from util import printf,fprintf
import servers
import string
import json
import util
import sys
import os


def usage(prog):
    printf("Usage is %s <id>\n",prog)
    printf("\n")
    printf("Deletes the cloud server\n")

if __name__ == "__main__":
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<2:
        usage(prog)
        sys.exit()
    id = int(sys.argv[1])
    s = servers.Servers()
    printf("%s\n",s.deleteServer(id))

    
