#!/usr/bin/env python

from util import printf,fprintf
import servers
import string
import json
import util
import sys
import os


def usage(prog):
    printf("Usage is %s <id> <passwd>\n",prog)
    printf("\n")
    printf("Reset the root password for the server specified by the id\n")

if __name__ == "__main__":
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<3:
        usage(prog)
        sys.exit()
    s = servers.Servers()
    id = int(sys.argv[1])
    passwd = sys.argv[2]
    resp = s.setPasswdServer(id,passwd)
    print resp
