#!/usr/bin/env python

from util import printf, fprintf
import traceback
import urllib2
import json
import sys
import os

def usage(prog):
    printf("usage is %s <first> <last>\n",prog)
    printf("\n")
    printf("Tests if the node up\n")


if __name__ == "__main__":
    prog = os.path.basename(sys.argv[0])
    if len(sys.argv)<3:
        usage(prog)
        sys.exit()
    first = int(sys.argv[1])
    last  = int(sys.argv[2])

    for i in xrange(first,last+1):
        url = "http://n%i.crc.m2linux.com/request/version"%i
        try:
            resp = json.loads(urllib2.urlopen(url).read())
            printf("node[%3i]:Version %s PASS\n",i,resp["version"])
        except KeyboardInterrupt:
            raise
        except:
            printf("node[%3i]:    FAIL\n",i)


